# https://github.com/khezen/compose-postgres
version: '3.5'

services:
    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: root
            PGDATA: /data/postgres
            MAX_WAL_SIZE: 500M
        volumes:
            - postgres:/data/postgres
        ports:
            - '5432:5432'
        networks:
            - postgres
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        logging:
            driver: 'none'
        volumes:
            - pgadmin:/var/lib/pgadmin

        ports:
            - '5050:80'
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin:
